import localFont from "next/font/local";
import "./globals.css";
import { Bebas_Neue, Montserrat } from 'next/font/google'
import NavBar from "./Components/NavBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const nexaFont = localFont({
  src:"./fonts/Nexa-Heavy.ttf",
  variable: "--font-nexa",
  weight:"100 900"
})

export const mont = Montserrat({subsets:['cyrillic'], adjustFontFallback:false, display:'swap'});
export const bebas = Bebas_Neue({subsets:['latin'], weight:['400'], adjustFontFallback:false});

 const metadata = {
  title: "PixelBridges",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nexaFont.variable} antialiased relative z-0 w-screen h-dvh overflow-hidden flex justify-center items-center`}
      >

      <div className=" sm1:w-[calc(100vw-30px)] w-[calc(100vw-15px)] sm1:h-[calc(100dvh-30px)] h-[calc(100dvh-15px)] sm:p-5 p-3 pt-3 flex flex-col justify-start items-center">
        <NavBar/>
        {children}
      </div>
      {/* <script src="https://kit.fontawesome.com/a90c6f7e11.js" crossOrigin="anonymous"></script> */}
      </body>
    </html>
  );
}
